name: 功能优化反馈 (Feature optimization feedback)
description: 提交一个功能优化需求帮助改进这个项目 (Submit a feature optimization request to help improve this project)
title: "[Perf] <在这里输入你的标题 (Enter your title here)>"
labels: ["performance"]
assignees:
  - teamssix
body:
- type: markdown
  attributes:
    value: |
      感谢您花时间提交这份 issue (Thanks for taking the time to fill out this bug report! )
- type: textarea
  id: performance
  attributes:
    label: 描述你希望优化的功能 (Describe the features you wish to optimize)
    value: "详细描述你希望优化的功能，并且描述为什么想要对这个功能进行优化，描述的越完善该反馈越有可能被采纳。(Describe in detail the feature you want to optimize and why you want to optimize it, the better the description the more likely the feedback will be accepted.)"
  validations:
    required: true
- type: textarea
  attributes:
    label: 补充信息 (Anything else?)
    description: |
      链接？参考资料？任何可以给我们提供更多关于你所遇到的问题的背景资料的东西
      Links? References? Anything that will give us more context about the issue you are encountering!

      提示：你可以通过点击这个区域来突出显示它，然后将文件拖入，从而附上图片或其他文件。
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
